name: fastocloud_dart_models
author: Alexandr Topilski <support@fastogt.com>
description: FastoCloud dart models.
version: 1.2.1+4

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta:

  fastotv_dart:
    git:
      url: https://github.com/fastogt/fastotv_dart.git
      ref: master

dev_dependencies:
  test: '>=1.15.3'
